name: scheduled-cron-job
on:
    schedule:
        - cron: '0 * * * *'
jobs:
    cron:
        runs-on: ubuntu-latest
        steps:
            - name: scheduled-cron-job
              run: |
                  curl -X POST 'https://coryd.dev/api/syndicate' \
                  -H 'Authorization: Bearer ${{ secrets.ACTION_KEY }}'
